name: 'Terraform Destroy'
 
on:
  workflow_dispatch:
 
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
 
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
 
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
 
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::838365449755:role/open-id-connect
          aws-region: eu-west-1
 
      - name: 'Terraform Init'
        run: terraform init
      - name: 'Terraform Plan Destroy'
        run: terraform plan -destroy
 
      - name: 'Terraform Destroy'
        run: terraform destroy -auto-approve
